### ISSUE TITLE
install problem at mac: curl: (6) Could not resolve host: v

### ISSUE THREAD

**Issue by atian25** [jasongin/nvs#25] opened 2017-01-10 04:57 UTC
![image](https://cloud.githubusercontent.com/assets/227713/21794330/55866dea-d734-11e6-8c51-a379b4a64c9a.png)

```shell
➜  ~ export NVS_HOME="$HOME/git/nvs"
➜  ~ git clone https://github.com/jasongin/nvs "$NVS_HOME"
Cloning into '/Users/tz/git/nvs'...
remote: Counting objects: 852, done.
remote: Total 852 (delta 0), reused 0 (delta 0), pack-reused 852
Receiving objects: 100% (852/852), 521.91 KiB | 70.00 KiB/s, done.
Resolving deltas: 100% (591/591), done.
➜  ~ . "$NVS_HOME/nvs.sh" install
grep: /Users/tz/defaults.json: No such file or directory
grep: /Users/tz/defaults.json: No such file or directory
grep: /Users/tz/defaults.json: No such file or directory
Downloading bootstrap node from v/node-v-darwin-x64.tar.xz

curl: (6) Could not resolve host: v
mv: rename /Users/tz/git/nvs/cache/node-v-darwin-x64/bin/node to /Users/tz/git/nvs/cache/node: No such file or directory
rm: /Users/tz/git/nvs/cache/node-v-darwin-x64: No such file or directory
Failed to download boostrap node binary.
➜  ~ nvs
grep: /Users/tz/defaults.json: No such file or directory
grep: /Users/tz/defaults.json: No such file or directory
grep: /Users/tz/defaults.json: No such file or directory
Downloading bootstrap node from v/node-v-darwin-x64.tar.xz

curl: (6) Could not resolve host: v
mv: rename /Users/tz/git/nvs/cache/node-v-darwin-x64/bin/node to /Users/tz/git/nvs/cache/node: No such file or directory
rm: /Users/tz/git/nvs/cache/node-v-darwin-x64: No such file or directory
Failed to download boostrap node binary.
```

**Comment by atian25** [comment] 2017-01-10 05:04
workaround: `wget https://github.com/jasongin/nvs/raw/master/defaults.json ~/defaults.json`

**Comment by atian25** [comment] 2017-01-10 05:08
new problem

```shell
➜  ~ echo $NVS_HOME
/Users/tz/git/nvs

➜  ~ nvs add lts
module.js:471
    throw err;
    ^

Error: Cannot find module '/Users/tz/lib/main.js'
```

**Comment by jasongin** [comment] 2017-01-10 17:22
@atian25 what shell are you using? (`echo $SHELL`) I think the problems are because the shell is something other than `bash`. I would like nvs to support other shells, but I have not tested them yet, so I'm not surprised there are issues. If I know what shell you're using then I can try to reproduce and fix the problem.

**Comment by jasongin** [comment] 2017-01-10 19:18
I made some changes in the nvs `develop` branch to improve POSIX compatibility of the shell script. I think that should fix your problem. Try this:
```
cd $NVS_HOME
git fetch
git checkout develop
. nvs.sh install
```
If you can confirm that works for you, I'll merge the fix to master.

**Comment by atian25** [comment] 2017-01-11 01:39
```shell
➜  nvs git:(develop) echo $SHELL
/bin/zsh

➜  nvs git:(master) git fetch
remote: Counting objects: 44, done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 44 (delta 5), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (44/44), done.
From https://github.com/jasongin/nvs
 * [new branch]      develop    -> origin/develop

➜  nvs git:(master) git checkout develop
Branch develop set up to track remote branch develop from origin.
Switched to a new branch 'develop'

➜  nvs git:(develop) . nvs.sh install
module.js:471
    throw err;
    ^

Error: Cannot find module '/Users/tz/lib/main.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by jasongin** [comment] 2017-01-11 17:30
Hmm, are you actually using zsh, or some other shell? I believe zsh normally has a `%` in the prompt by default, unless you've customized it to ➜. When I tested with zsh (with the nvs `develop` branch) I didn't have any problem.

Anyway, I think the issue now is the `NVS_ROOT` environment variable is still set incorrectly due to the previous script errors. Try this:

```
unset NVS_ROOT
. "$NVS_HOME/nvs.sh" install
```

(Note `NVS_ROOT` is distinct from `NVS_HOME`; by default they are the same but they can be set to different paths if you need to store downloaded node binaries at `NVS_HOME` in a different location from the nvs scripts at `NVS_ROOT`.)

**Comment by atian25** [comment] 2017-01-12 02:45
I'm using oh-my-zsh.

yes it works now.

**Comment by jasongin** [comment] 2017-01-12 17:27
Great, thanks for confirming!
I merged the fix to the master branch; I recommend switching back to that branch to get future stable updates:
```
cd $NVS_HOME
git fetch
git checkout master
```

**Closed by jasongin** 2017-01-12 17:27 UTC
