### ISSUE TITLE
permission issue with nvs add (Win 10 nvs-1.4.2)

### ISSUE THREAD

**Issue by fobbyal** [jasongin/nvs#71] opened 2017-09-16 15:15 UTC
just installed latest nvs(1.4.2) on a new windows 10 install which had no node. The nvs add command is producing this error in both Run-As-Admin powershell and regular powershell. Checked the permissions and it seems everything is okay. Not really sure what is going on here. Am I doing something wrong?

It does not seem that the installation was completed because npm does not work when execute the `use` command.

command screenshot
![image](https://user-images.githubusercontent.com/7818365/30513337-83998492-9acf-11e7-819a-fb5b52b517df.png)
node install dir

![image](https://user-images.githubusercontent.com/7818365/30513353-d7bc3132-9acf-11e7-8efa-d060b1ce63e9.png)

both local user and Administrator has full control

![image](https://user-images.githubusercontent.com/7818365/30513368-0cdf0c7c-9ad0-11e7-844a-22e44e708cec.png)

**Comment by jasongin** [comment] 2017-09-18 03:14
Sorry, I'm not sure what could have caused that error. Are you able to manually move the named directory? (Does it exist?)

I suspect the `EPERM` reported by `fs.renameSync()` might be the wrong error code. Maybe the source directory to be renamed didn't exist, because the download was truncated? Can you try again after clearing the download cache? Delete all files from `AppData\Local\nvs\cache`.

**Comment by fobbyal** [comment] 2017-09-18 04:45
I played with it a bit more today. and I was able to get things working by moving everything under 

* `c:\users\%USER%\AppData\Local\nvs\node\6.11.3\x64\node-v6.11.3-win-x64` to 

* `c:\users\%USER%\AppData\Local\nvs\node\6.11.3\x64`

The strange thing is that. After i fixed that install. the other installs started working...
not really sure what is going here. It's your choice to close this one. I spent a few hours before posting so there might be a underline issue. Anyways, all things are good now.

Thank you for such a great tool under windows!!!!

**Comment by jasongin** [comment] 2017-09-19 17:41
Closing for now since it's resolved and I can't reproduce the problem. I'll keep an eye out for this issue. And if anyone else experiences this, please reopen and provide as much detail as you can.

**Closed by jasongin** 2017-09-19 17:41 UTC
